# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Display
version:      0.38
version_from: lib/HTML/Display.pm
installdirs:  site
requires:
    HTML::TokeParser::Simple:      2
    LWP:                           5.69
    parent:                        0.218
    Test::Harness:                 2.3
    URI::URL:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
