---
abstract: 'display HTML locally in a browser'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Display
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TokeParser::Simple: 2
  LWP: 5.69
  Test::Harness: 2.3
  URI::URL: 0
  parent: 0.218
version: 0.40
